// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: layerone.proto

package layerone

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LayerOneClient is the client API for LayerOne service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LayerOneClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadReply, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteReply, error)
}

type layerOneClient struct {
	cc grpc.ClientConnInterface
}

func NewLayerOneClient(cc grpc.ClientConnInterface) LayerOneClient {
	return &layerOneClient{cc}
}

func (c *layerOneClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadReply, error) {
	out := new(ReadReply)
	err := c.cc.Invoke(ctx, "/layerone.LayerOne/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerOneClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteReply, error) {
	out := new(WriteReply)
	err := c.cc.Invoke(ctx, "/layerone.LayerOne/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LayerOneServer is the server API for LayerOne service.
// All implementations must embed UnimplementedLayerOneServer
// for forward compatibility
type LayerOneServer interface {
	Read(context.Context, *ReadRequest) (*ReadReply, error)
	Write(context.Context, *WriteRequest) (*WriteReply, error)
	mustEmbedUnimplementedLayerOneServer()
}

// UnimplementedLayerOneServer must be embedded to have forward compatible implementations.
type UnimplementedLayerOneServer struct {
}

func (UnimplementedLayerOneServer) Read(context.Context, *ReadRequest) (*ReadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedLayerOneServer) Write(context.Context, *WriteRequest) (*WriteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedLayerOneServer) mustEmbedUnimplementedLayerOneServer() {}

// UnsafeLayerOneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LayerOneServer will
// result in compilation errors.
type UnsafeLayerOneServer interface {
	mustEmbedUnimplementedLayerOneServer()
}

func RegisterLayerOneServer(s grpc.ServiceRegistrar, srv LayerOneServer) {
	s.RegisterService(&LayerOne_ServiceDesc, srv)
}

func _LayerOne_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerOneServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/layerone.LayerOne/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerOneServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerOne_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerOneServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/layerone.LayerOne/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerOneServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LayerOne_ServiceDesc is the grpc.ServiceDesc for LayerOne service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LayerOne_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "layerone.LayerOne",
	HandlerType: (*LayerOneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _LayerOne_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _LayerOne_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "layerone.proto",
}
