// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: shardnode.proto

package shardnode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShardNodeClient is the client API for ShardNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardNodeClient interface {
	ReadPath(ctx context.Context, in *ReadPathRequest, opts ...grpc.CallOption) (*ReadPathReply, error)
	JoinRaftVoter(ctx context.Context, in *JoinRaftVoterRequest, opts ...grpc.CallOption) (*JoinRaftVoterReply, error)
}

type shardNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewShardNodeClient(cc grpc.ClientConnInterface) ShardNodeClient {
	return &shardNodeClient{cc}
}

func (c *shardNodeClient) ReadPath(ctx context.Context, in *ReadPathRequest, opts ...grpc.CallOption) (*ReadPathReply, error) {
	out := new(ReadPathReply)
	err := c.cc.Invoke(ctx, "/shardnode.ShardNode/ReadPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardNodeClient) JoinRaftVoter(ctx context.Context, in *JoinRaftVoterRequest, opts ...grpc.CallOption) (*JoinRaftVoterReply, error) {
	out := new(JoinRaftVoterReply)
	err := c.cc.Invoke(ctx, "/shardnode.ShardNode/JoinRaftVoter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardNodeServer is the server API for ShardNode service.
// All implementations must embed UnimplementedShardNodeServer
// for forward compatibility
type ShardNodeServer interface {
	ReadPath(context.Context, *ReadPathRequest) (*ReadPathReply, error)
	JoinRaftVoter(context.Context, *JoinRaftVoterRequest) (*JoinRaftVoterReply, error)
	mustEmbedUnimplementedShardNodeServer()
}

// UnimplementedShardNodeServer must be embedded to have forward compatible implementations.
type UnimplementedShardNodeServer struct {
}

func (UnimplementedShardNodeServer) ReadPath(context.Context, *ReadPathRequest) (*ReadPathReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPath not implemented")
}
func (UnimplementedShardNodeServer) JoinRaftVoter(context.Context, *JoinRaftVoterRequest) (*JoinRaftVoterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRaftVoter not implemented")
}
func (UnimplementedShardNodeServer) mustEmbedUnimplementedShardNodeServer() {}

// UnsafeShardNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardNodeServer will
// result in compilation errors.
type UnsafeShardNodeServer interface {
	mustEmbedUnimplementedShardNodeServer()
}

func RegisterShardNodeServer(s grpc.ServiceRegistrar, srv ShardNodeServer) {
	s.RegisterService(&ShardNode_ServiceDesc, srv)
}

func _ShardNode_ReadPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardNodeServer).ReadPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shardnode.ShardNode/ReadPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardNodeServer).ReadPath(ctx, req.(*ReadPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardNode_JoinRaftVoter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRaftVoterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardNodeServer).JoinRaftVoter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shardnode.ShardNode/JoinRaftVoter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardNodeServer).JoinRaftVoter(ctx, req.(*JoinRaftVoterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShardNode_ServiceDesc is the grpc.ServiceDesc for ShardNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shardnode.ShardNode",
	HandlerType: (*ShardNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadPath",
			Handler:    _ShardNode_ReadPath_Handler,
		},
		{
			MethodName: "JoinRaftVoter",
			Handler:    _ShardNode_JoinRaftVoter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shardnode.proto",
}
