// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: layertwo.proto

package layertwo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LayerTwoClient is the client API for LayerTwo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LayerTwoClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadReply, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteReply, error)
}

type layerTwoClient struct {
	cc grpc.ClientConnInterface
}

func NewLayerTwoClient(cc grpc.ClientConnInterface) LayerTwoClient {
	return &layerTwoClient{cc}
}

func (c *layerTwoClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadReply, error) {
	out := new(ReadReply)
	err := c.cc.Invoke(ctx, "/layertwo.LayerTwo/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerTwoClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteReply, error) {
	out := new(WriteReply)
	err := c.cc.Invoke(ctx, "/layertwo.LayerTwo/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LayerTwoServer is the server API for LayerTwo service.
// All implementations must embed UnimplementedLayerTwoServer
// for forward compatibility
type LayerTwoServer interface {
	Read(context.Context, *ReadRequest) (*ReadReply, error)
	Write(context.Context, *WriteRequest) (*WriteReply, error)
	mustEmbedUnimplementedLayerTwoServer()
}

// UnimplementedLayerTwoServer must be embedded to have forward compatible implementations.
type UnimplementedLayerTwoServer struct {
}

func (UnimplementedLayerTwoServer) Read(context.Context, *ReadRequest) (*ReadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedLayerTwoServer) Write(context.Context, *WriteRequest) (*WriteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedLayerTwoServer) mustEmbedUnimplementedLayerTwoServer() {}

// UnsafeLayerTwoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LayerTwoServer will
// result in compilation errors.
type UnsafeLayerTwoServer interface {
	mustEmbedUnimplementedLayerTwoServer()
}

func RegisterLayerTwoServer(s grpc.ServiceRegistrar, srv LayerTwoServer) {
	s.RegisterService(&LayerTwo_ServiceDesc, srv)
}

func _LayerTwo_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerTwoServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/layertwo.LayerTwo/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerTwoServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerTwo_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerTwoServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/layertwo.LayerTwo/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerTwoServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LayerTwo_ServiceDesc is the grpc.ServiceDesc for LayerTwo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LayerTwo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "layertwo.LayerTwo",
	HandlerType: (*LayerTwoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _LayerTwo_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _LayerTwo_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "layertwo.proto",
}
