// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router.proto

package site.ycsb.db;

public interface ReadReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:router.ReadReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
