// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: router.proto

package site.ycsb.db;

public interface WriteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:router.WriteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string block = 1;</code>
   * @return The block.
   */
  java.lang.String getBlock();
  /**
   * <code>string block = 1;</code>
   * @return The bytes for block.
   */
  com.google.protobuf.ByteString
      getBlockBytes();

  /**
   * <code>string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
