// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: leadernotif.proto

package leadernotif

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeLayer string `protobuf:"bytes,1,opt,name=node_layer,json=nodeLayer,proto3" json:"node_layer,omitempty"`
	Id        int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	LeaderId  int32  `protobuf:"varint,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leadernotif_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leadernotif_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_leadernotif_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetNodeLayer() string {
	if x != nil {
		return x.NodeLayer
	}
	return ""
}

func (x *PublishRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublishRequest) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type PublishReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PublishReply) Reset() {
	*x = PublishReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leadernotif_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReply) ProtoMessage() {}

func (x *PublishReply) ProtoReflect() protoreflect.Message {
	mi := &file_leadernotif_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReply.ProtoReflect.Descriptor instead.
func (*PublishReply) Descriptor() ([]byte, []int) {
	return file_leadernotif_proto_rawDescGZIP(), []int{1}
}

func (x *PublishReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeLayer string `protobuf:"bytes,1,opt,name=node_layer,json=nodeLayer,proto3" json:"node_layer,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leadernotif_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leadernotif_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_leadernotif_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetNodeLayer() string {
	if x != nil {
		return x.NodeLayer
	}
	return ""
}

type LeaderChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaderId int32 `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Id       int32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"` // the shard node id or the oram node id
}

func (x *LeaderChange) Reset() {
	*x = LeaderChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leadernotif_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderChange) ProtoMessage() {}

func (x *LeaderChange) ProtoReflect() protoreflect.Message {
	mi := &file_leadernotif_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderChange.ProtoReflect.Descriptor instead.
func (*LeaderChange) Descriptor() ([]byte, []int) {
	return file_leadernotif_proto_rawDescGZIP(), []int{3}
}

func (x *LeaderChange) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *LeaderChange) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_leadernotif_proto protoreflect.FileDescriptor

var file_leadernotif_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x22, 0x5c, 0x0a, 0x0e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x79, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x28,
	0x0a, 0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x31, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x3b, 0x0a, 0x0c, 0x4c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x32, 0x9d, 0x01, 0x0a, 0x0b, 0x4c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x12, 0x43, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x12, 0x1b, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x2e, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x49, 0x0a,
	0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x1d, 0x2e, 0x6c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x73, 0x67, 0x2d, 0x75, 0x77, 0x61, 0x74, 0x65,
	0x72, 0x6c, 0x6f, 0x6f, 0x2f, 0x6f, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x61, 0x72, 0x64, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_leadernotif_proto_rawDescOnce sync.Once
	file_leadernotif_proto_rawDescData = file_leadernotif_proto_rawDesc
)

func file_leadernotif_proto_rawDescGZIP() []byte {
	file_leadernotif_proto_rawDescOnce.Do(func() {
		file_leadernotif_proto_rawDescData = protoimpl.X.CompressGZIP(file_leadernotif_proto_rawDescData)
	})
	return file_leadernotif_proto_rawDescData
}

var file_leadernotif_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_leadernotif_proto_goTypes = []interface{}{
	(*PublishRequest)(nil),   // 0: leadernotif.PublishRequest
	(*PublishReply)(nil),     // 1: leadernotif.PublishReply
	(*SubscribeRequest)(nil), // 2: leadernotif.SubscribeRequest
	(*LeaderChange)(nil),     // 3: leadernotif.LeaderChange
}
var file_leadernotif_proto_depIdxs = []int32{
	0, // 0: leadernotif.LeaderNotif.Publish:input_type -> leadernotif.PublishRequest
	2, // 1: leadernotif.LeaderNotif.Subscribe:input_type -> leadernotif.SubscribeRequest
	1, // 2: leadernotif.LeaderNotif.Publish:output_type -> leadernotif.PublishReply
	3, // 3: leadernotif.LeaderNotif.Subscribe:output_type -> leadernotif.LeaderChange
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_leadernotif_proto_init() }
func file_leadernotif_proto_init() {
	if File_leadernotif_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_leadernotif_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leadernotif_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leadernotif_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leadernotif_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_leadernotif_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leadernotif_proto_goTypes,
		DependencyIndexes: file_leadernotif_proto_depIdxs,
		MessageInfos:      file_leadernotif_proto_msgTypes,
	}.Build()
	File_leadernotif_proto = out.File
	file_leadernotif_proto_rawDesc = nil
	file_leadernotif_proto_goTypes = nil
	file_leadernotif_proto_depIdxs = nil
}
